// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paid_queries.sql

package paidjobdb

import (
	"context"
)

const paidChargeOrdersToStart = `-- name: PaidChargeOrdersToStart :many
SELECT c.id, c.order_no
FROM charge_order AS c
JOIN charge_payment_intent AS i ON i.charge_order_id = c.id
  AND i.user_id = c.user_id AND i.status = 'paid'
JOIN payment_order AS p ON p.id = i.payment_order_id
  AND p.biz_type = 'charge' AND p.biz_id = c.id
  AND p.user_id = c.user_id AND p.status = 'paid'
  AND p.total_cents > 0 AND p.paid_cents >= p.total_cents
WHERE c.status = 'paid' AND c.deleted_at IS NULL
  AND c.id > ?
ORDER BY c.id
LIMIT 100
`

type PaidChargeOrdersToStartRow struct {
	ID      uint64
	OrderNo string
}

func (q *Queries) PaidChargeOrdersToStart(ctx context.Context, id uint64) ([]PaidChargeOrdersToStartRow, error) {
	rows, err := q.db.QueryContext(ctx, paidChargeOrdersToStart, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaidChargeOrdersToStartRow
	for rows.Next() {
		var i PaidChargeOrdersToStartRow
		if err := rows.Scan(&i.ID, &i.OrderNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
