// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_queries.sql

package paymentdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const bindPaymentToCharge = `-- name: BindPaymentToCharge :execresult
UPDATE payment_order SET biz_id = ? WHERE id = ? AND biz_id = 0 AND status = 'paid'
`

type BindPaymentToChargeParams struct {
	BizID uint64
	ID    uint64
}

func (q *Queries) BindPaymentToCharge(ctx context.Context, arg BindPaymentToChargeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, bindPaymentToCharge, arg.BizID, arg.ID)
}

const callbackDigestByTransaction = `-- name: CallbackDigestByTransaction :one
SELECT request_digest FROM payment_callback_idempotent
WHERE wechat_transaction_id = ? LIMIT 1
`

func (q *Queries) CallbackDigestByTransaction(ctx context.Context, wechatTransactionID string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, callbackDigestByTransaction, wechatTransactionID)
	var request_digest sql.NullString
	err := row.Scan(&request_digest)
	return request_digest, err
}

const createChargeOrderFromPayment = `-- name: CreateChargeOrderFromPayment :execresult
INSERT INTO charge_order
  (order_no, user_id, device_id, port_no, port_code, payment_order_id,
   status, charge_mode, charge_quantity, created_month)
VALUES (?, ?, ?, ?, ?, ?, 'paid', ?, ?, UTC_DATE())
`

type CreateChargeOrderFromPaymentParams struct {
	OrderNo        string
	UserID         uint64
	DeviceID       string
	PortNo         uint8
	PortCode       sql.NullString
	PaymentOrderID sql.NullInt64
	ChargeMode     sql.NullInt16
	ChargeQuantity sql.NullInt16
}

func (q *Queries) CreateChargeOrderFromPayment(ctx context.Context, arg CreateChargeOrderFromPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChargeOrderFromPayment,
		arg.OrderNo,
		arg.UserID,
		arg.DeviceID,
		arg.PortNo,
		arg.PortCode,
		arg.PaymentOrderID,
		arg.ChargeMode,
		arg.ChargeQuantity,
	)
}

const expireStaleIntents = `-- name: ExpireStaleIntents :exec
UPDATE charge_payment_intent SET status = 'expired'
WHERE status = 'initiated' AND expires_at < NOW(3)
`

func (q *Queries) ExpireStaleIntents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireStaleIntents)
	return err
}

const insertCallbackDigest = `-- name: InsertCallbackDigest :exec
INSERT INTO payment_callback_idempotent (wechat_transaction_id, request_digest)
VALUES (?, ?)
`

type InsertCallbackDigestParams struct {
	WechatTransactionID string
	RequestDigest       sql.NullString
}

func (q *Queries) InsertCallbackDigest(ctx context.Context, arg InsertCallbackDigestParams) error {
	_, err := q.db.ExecContext(ctx, insertCallbackDigest, arg.WechatTransactionID, arg.RequestDigest)
	return err
}

const insertChargePaymentIntent = `-- name: InsertChargePaymentIntent :exec
INSERT INTO charge_payment_intent
  (intent_id, client_request_id, merchant_order_no, payment_order_id,
   user_id, openid, device_id, port_no, port_code, station_id,
   pricing_rule_id, pricing_rule_version, pricing_snapshot,
   estimated_kwh, estimated_minutes, electric_cents, service_cents,
   total_cents, charge_mode, charge_quantity, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS DECIMAL(9,3)),
        ?, ?, ?, ?, ?, ?, ?)
`

type InsertChargePaymentIntentParams struct {
	IntentID           string
	ClientRequestID    string
	MerchantOrderNo    string
	PaymentOrderID     uint64
	UserID             uint64
	Openid             string
	DeviceID           string
	PortNo             uint8
	PortCode           string
	StationID          uint64
	PricingRuleID      uint64
	PricingRuleVersion uint32
	PricingSnapshot    json.RawMessage
	EstimatedKwh       string
	EstimatedMinutes   uint16
	ElectricCents      int64
	ServiceCents       int64
	TotalCents         int64
	ChargeMode         uint8
	ChargeQuantity     uint16
	ExpiresAt          time.Time
}

func (q *Queries) InsertChargePaymentIntent(ctx context.Context, arg InsertChargePaymentIntentParams) error {
	_, err := q.db.ExecContext(ctx, insertChargePaymentIntent,
		arg.IntentID,
		arg.ClientRequestID,
		arg.MerchantOrderNo,
		arg.PaymentOrderID,
		arg.UserID,
		arg.Openid,
		arg.DeviceID,
		arg.PortNo,
		arg.PortCode,
		arg.StationID,
		arg.PricingRuleID,
		arg.PricingRuleVersion,
		arg.PricingSnapshot,
		arg.EstimatedKwh,
		arg.EstimatedMinutes,
		arg.ElectricCents,
		arg.ServiceCents,
		arg.TotalCents,
		arg.ChargeMode,
		arg.ChargeQuantity,
		arg.ExpiresAt,
	)
	return err
}

const insertChargePricingSnapshot = `-- name: InsertChargePricingSnapshot :exec
INSERT INTO charge_order_pricing
  (charge_order_id, payment_intent_id, user_id, port_code, pricing_snapshot)
VALUES (?, ?, ?, ?, ?)
`

type InsertChargePricingSnapshotParams struct {
	ChargeOrderID   uint64
	PaymentIntentID string
	UserID          uint64
	PortCode        string
	PricingSnapshot json.RawMessage
}

func (q *Queries) InsertChargePricingSnapshot(ctx context.Context, arg InsertChargePricingSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertChargePricingSnapshot,
		arg.ChargeOrderID,
		arg.PaymentIntentID,
		arg.UserID,
		arg.PortCode,
		arg.PricingSnapshot,
	)
	return err
}

const insertLatePaymentRefund = `-- name: InsertLatePaymentRefund :exec
INSERT INTO refund_record
  (refund_no, payment_order_id, user_id, biz_type, biz_id,
   refund_cents, reason, status, created_month)
VALUES (?, ?, ?, 'charge', 0, ?, 'payment arrived after intent expired',
        'pending', UTC_DATE())
`

type InsertLatePaymentRefundParams struct {
	RefundNo       string
	PaymentOrderID uint64
	UserID         uint64
	RefundCents    int64
}

func (q *Queries) InsertLatePaymentRefund(ctx context.Context, arg InsertLatePaymentRefundParams) error {
	_, err := q.db.ExecContext(ctx, insertLatePaymentRefund,
		arg.RefundNo,
		arg.PaymentOrderID,
		arg.UserID,
		arg.RefundCents,
	)
	return err
}

const insertPaymentChargeEvent = `-- name: InsertPaymentChargeEvent :exec
INSERT INTO charge_event_log
  (charge_order_id, event_id, event, actor, detail, occurred_at)
VALUES (?, ?, ?, 'payment_callback', ?, ?)
`

type InsertPaymentChargeEventParams struct {
	ChargeOrderID uint64
	EventID       string
	Event         string
	Detail        string
	OccurredAt    time.Time
}

func (q *Queries) InsertPaymentChargeEvent(ctx context.Context, arg InsertPaymentChargeEventParams) error {
	_, err := q.db.ExecContext(ctx, insertPaymentChargeEvent,
		arg.ChargeOrderID,
		arg.EventID,
		arg.Event,
		arg.Detail,
		arg.OccurredAt,
	)
	return err
}

const insertPaymentOrderForIntent = `-- name: InsertPaymentOrderForIntent :execresult
INSERT INTO payment_order
  (order_no, biz_type, biz_id, user_id, pay_method, total_cents,
   status, expired_at, created_month)
VALUES (?, 'charge', 0, ?, 'wechat', ?, 'initiated', ?, UTC_DATE())
`

type InsertPaymentOrderForIntentParams struct {
	OrderNo    string
	UserID     uint64
	TotalCents int64
	ExpiredAt  sql.NullTime
}

func (q *Queries) InsertPaymentOrderForIntent(ctx context.Context, arg InsertPaymentOrderForIntentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPaymentOrderForIntent,
		arg.OrderNo,
		arg.UserID,
		arg.TotalCents,
		arg.ExpiredAt,
	)
}

const insertPaymentOutbox = `-- name: InsertPaymentOutbox :exec
INSERT INTO event_outbox (event_id, stream, envelope_json)
VALUES (?, ?, ?)
`

type InsertPaymentOutboxParams struct {
	EventID      string
	Stream       string
	EnvelopeJson json.RawMessage
}

func (q *Queries) InsertPaymentOutbox(ctx context.Context, arg InsertPaymentOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertPaymentOutbox, arg.EventID, arg.Stream, arg.EnvelopeJson)
	return err
}

const intentForSimulation = `-- name: IntentForSimulation :one
SELECT intent_id, merchant_order_no, openid, total_cents, status, expires_at
FROM charge_payment_intent WHERE merchant_order_no = ? LIMIT 1
`

type IntentForSimulationRow struct {
	IntentID        string
	MerchantOrderNo string
	Openid          string
	TotalCents      int64
	Status          ChargePaymentIntentStatus
	ExpiresAt       time.Time
}

func (q *Queries) IntentForSimulation(ctx context.Context, merchantOrderNo string) (IntentForSimulationRow, error) {
	row := q.db.QueryRowContext(ctx, intentForSimulation, merchantOrderNo)
	var i IntentForSimulationRow
	err := row.Scan(
		&i.IntentID,
		&i.MerchantOrderNo,
		&i.Openid,
		&i.TotalCents,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const lockIntentForCallback = `-- name: LockIntentForCallback :one
SELECT intent_id, merchant_order_no, payment_order_id, user_id, openid,
       device_id, port_no, port_code, pricing_snapshot, total_cents,
       charge_mode, charge_quantity, status, expires_at, charge_order_id
FROM charge_payment_intent WHERE merchant_order_no = ? LIMIT 1 FOR UPDATE
`

type LockIntentForCallbackRow struct {
	IntentID        string
	MerchantOrderNo string
	PaymentOrderID  uint64
	UserID          uint64
	Openid          string
	DeviceID        string
	PortNo          uint8
	PortCode        string
	PricingSnapshot json.RawMessage
	TotalCents      int64
	ChargeMode      uint8
	ChargeQuantity  uint16
	Status          ChargePaymentIntentStatus
	ExpiresAt       time.Time
	ChargeOrderID   sql.NullInt64
}

func (q *Queries) LockIntentForCallback(ctx context.Context, merchantOrderNo string) (LockIntentForCallbackRow, error) {
	row := q.db.QueryRowContext(ctx, lockIntentForCallback, merchantOrderNo)
	var i LockIntentForCallbackRow
	err := row.Scan(
		&i.IntentID,
		&i.MerchantOrderNo,
		&i.PaymentOrderID,
		&i.UserID,
		&i.Openid,
		&i.DeviceID,
		&i.PortNo,
		&i.PortCode,
		&i.PricingSnapshot,
		&i.TotalCents,
		&i.ChargeMode,
		&i.ChargeQuantity,
		&i.Status,
		&i.ExpiresAt,
		&i.ChargeOrderID,
	)
	return i, err
}

const lockPaymentForCallback = `-- name: LockPaymentForCallback :one
SELECT id, order_no, biz_id, user_id, total_cents, paid_cents,
       wechat_transaction_id, status
FROM payment_order WHERE id = ? AND order_no = ?
LIMIT 1 FOR UPDATE
`

type LockPaymentForCallbackParams struct {
	ID      uint64
	OrderNo string
}

type LockPaymentForCallbackRow struct {
	ID                  uint64
	OrderNo             string
	BizID               uint64
	UserID              uint64
	TotalCents          int64
	PaidCents           int64
	WechatTransactionID sql.NullString
	Status              PaymentOrderStatus
}

func (q *Queries) LockPaymentForCallback(ctx context.Context, arg LockPaymentForCallbackParams) (LockPaymentForCallbackRow, error) {
	row := q.db.QueryRowContext(ctx, lockPaymentForCallback, arg.ID, arg.OrderNo)
	var i LockPaymentForCallbackRow
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.BizID,
		&i.UserID,
		&i.TotalCents,
		&i.PaidCents,
		&i.WechatTransactionID,
		&i.Status,
	)
	return i, err
}

const markIntentPaid = `-- name: MarkIntentPaid :execresult
UPDATE charge_payment_intent SET status = 'paid', paid_at = ?, charge_order_id = ?
WHERE intent_id = ? AND status = 'initiated' AND charge_order_id IS NULL
`

type MarkIntentPaidParams struct {
	PaidAt        sql.NullTime
	ChargeOrderID sql.NullInt64
	IntentID      string
}

func (q *Queries) MarkIntentPaid(ctx context.Context, arg MarkIntentPaidParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markIntentPaid, arg.PaidAt, arg.ChargeOrderID, arg.IntentID)
}

const markIntentRefundRequired = `-- name: MarkIntentRefundRequired :execresult
UPDATE charge_payment_intent SET status = 'refund_required', paid_at = ?
WHERE intent_id = ? AND status IN ('initiated','expired')
`

type MarkIntentRefundRequiredParams struct {
	PaidAt   sql.NullTime
	IntentID string
}

func (q *Queries) MarkIntentRefundRequired(ctx context.Context, arg MarkIntentRefundRequiredParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markIntentRefundRequired, arg.PaidAt, arg.IntentID)
}

const markPaymentPaidByCallback = `-- name: MarkPaymentPaidByCallback :execresult
UPDATE payment_order SET status = 'paid', paid_cents = ?,
  wechat_transaction_id = ?, paid_at = ?
WHERE id = ? AND order_no = ? AND status = 'initiated'
  AND total_cents = ? AND paid_cents = 0
`

type MarkPaymentPaidByCallbackParams struct {
	PaidCents           int64
	WechatTransactionID sql.NullString
	PaidAt              sql.NullTime
	ID                  uint64
	OrderNo             string
	TotalCents          int64
}

func (q *Queries) MarkPaymentPaidByCallback(ctx context.Context, arg MarkPaymentPaidByCallbackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markPaymentPaidByCallback,
		arg.PaidCents,
		arg.WechatTransactionID,
		arg.PaidAt,
		arg.ID,
		arg.OrderNo,
		arg.TotalCents,
	)
}

const paymentIntentByRequest = `-- name: PaymentIntentByRequest :one
SELECT intent_id, merchant_order_no, payment_order_id, user_id, openid,
       device_id, port_no, port_code, station_id, pricing_rule_id,
       pricing_rule_version, pricing_snapshot, estimated_kwh,
       estimated_minutes, electric_cents, service_cents, total_cents,
       charge_mode, charge_quantity, status, expires_at
FROM charge_payment_intent
WHERE user_id = ? AND client_request_id = ? LIMIT 1
`

type PaymentIntentByRequestParams struct {
	UserID          uint64
	ClientRequestID string
}

type PaymentIntentByRequestRow struct {
	IntentID           string
	MerchantOrderNo    string
	PaymentOrderID     uint64
	UserID             uint64
	Openid             string
	DeviceID           string
	PortNo             uint8
	PortCode           string
	StationID          uint64
	PricingRuleID      uint64
	PricingRuleVersion uint32
	PricingSnapshot    json.RawMessage
	EstimatedKwh       string
	EstimatedMinutes   uint16
	ElectricCents      int64
	ServiceCents       int64
	TotalCents         int64
	ChargeMode         uint8
	ChargeQuantity     uint16
	Status             ChargePaymentIntentStatus
	ExpiresAt          time.Time
}

func (q *Queries) PaymentIntentByRequest(ctx context.Context, arg PaymentIntentByRequestParams) (PaymentIntentByRequestRow, error) {
	row := q.db.QueryRowContext(ctx, paymentIntentByRequest, arg.UserID, arg.ClientRequestID)
	var i PaymentIntentByRequestRow
	err := row.Scan(
		&i.IntentID,
		&i.MerchantOrderNo,
		&i.PaymentOrderID,
		&i.UserID,
		&i.Openid,
		&i.DeviceID,
		&i.PortNo,
		&i.PortCode,
		&i.StationID,
		&i.PricingRuleID,
		&i.PricingRuleVersion,
		&i.PricingSnapshot,
		&i.EstimatedKwh,
		&i.EstimatedMinutes,
		&i.ElectricCents,
		&i.ServiceCents,
		&i.TotalCents,
		&i.ChargeMode,
		&i.ChargeQuantity,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const prepayByPaymentOrder = `-- name: PrepayByPaymentOrder :one
SELECT params_json FROM charge_prepay WHERE payment_order_id = ? LIMIT 1
`

func (q *Queries) PrepayByPaymentOrder(ctx context.Context, paymentOrderID uint64) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, prepayByPaymentOrder, paymentOrderID)
	var params_json json.RawMessage
	err := row.Scan(&params_json)
	return params_json, err
}

const savePrepay = `-- name: SavePrepay :exec
INSERT INTO charge_prepay (payment_order_id, params_json, prepay_id)
VALUES (?, ?, ?)
ON DUPLICATE KEY UPDATE payment_order_id = payment_order_id
`

type SavePrepayParams struct {
	PaymentOrderID uint64
	ParamsJson     json.RawMessage
	PrepayID       sql.NullString
}

func (q *Queries) SavePrepay(ctx context.Context, arg SavePrepayParams) error {
	_, err := q.db.ExecContext(ctx, savePrepay, arg.PaymentOrderID, arg.ParamsJson, arg.PrepayID)
	return err
}

const userOpenID = `-- name: UserOpenID :one
SELECT openid FROM user WHERE id = ? AND status = 'active' AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) UserOpenID(ctx context.Context, id uint64) (string, error) {
	row := q.db.QueryRowContext(ctx, userOpenID, id)
	var openid string
	err := row.Scan(&openid)
	return openid, err
}
