// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_queries.sql

package paymentdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const expireStaleIntents = `-- name: ExpireStaleIntents :exec
UPDATE charge_payment_intent SET status = 'expired'
WHERE status = 'initiated' AND expires_at < NOW(3)
`

func (q *Queries) ExpireStaleIntents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireStaleIntents)
	return err
}

const insertChargePaymentIntent = `-- name: InsertChargePaymentIntent :exec
INSERT INTO charge_payment_intent
  (intent_id, client_request_id, merchant_order_no, payment_order_id,
   user_id, openid, device_id, port_no, port_code, station_id,
   pricing_rule_id, pricing_rule_version, pricing_snapshot,
   estimated_kwh, estimated_minutes, electric_cents, service_cents,
   total_cents, charge_mode, charge_quantity, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CAST(? AS DECIMAL(9,3)),
        ?, ?, ?, ?, ?, ?, ?)
`

type InsertChargePaymentIntentParams struct {
	IntentID           string
	ClientRequestID    string
	MerchantOrderNo    string
	PaymentOrderID     uint64
	UserID             uint64
	Openid             string
	DeviceID           string
	PortNo             uint8
	PortCode           string
	StationID          uint64
	PricingRuleID      uint64
	PricingRuleVersion uint32
	PricingSnapshot    json.RawMessage
	EstimatedKwh       string
	EstimatedMinutes   uint16
	ElectricCents      int64
	ServiceCents       int64
	TotalCents         int64
	ChargeMode         uint8
	ChargeQuantity     uint16
	ExpiresAt          time.Time
}

func (q *Queries) InsertChargePaymentIntent(ctx context.Context, arg InsertChargePaymentIntentParams) error {
	_, err := q.db.ExecContext(ctx, insertChargePaymentIntent,
		arg.IntentID,
		arg.ClientRequestID,
		arg.MerchantOrderNo,
		arg.PaymentOrderID,
		arg.UserID,
		arg.Openid,
		arg.DeviceID,
		arg.PortNo,
		arg.PortCode,
		arg.StationID,
		arg.PricingRuleID,
		arg.PricingRuleVersion,
		arg.PricingSnapshot,
		arg.EstimatedKwh,
		arg.EstimatedMinutes,
		arg.ElectricCents,
		arg.ServiceCents,
		arg.TotalCents,
		arg.ChargeMode,
		arg.ChargeQuantity,
		arg.ExpiresAt,
	)
	return err
}

const insertPaymentOrderForIntent = `-- name: InsertPaymentOrderForIntent :execresult
INSERT INTO payment_order
  (order_no, biz_type, biz_id, user_id, pay_method, total_cents,
   status, expired_at, created_month)
VALUES (?, 'charge', 0, ?, 'wechat', ?, 'initiated', ?, UTC_DATE())
`

type InsertPaymentOrderForIntentParams struct {
	OrderNo    string
	UserID     uint64
	TotalCents int64
	ExpiredAt  sql.NullTime
}

func (q *Queries) InsertPaymentOrderForIntent(ctx context.Context, arg InsertPaymentOrderForIntentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPaymentOrderForIntent,
		arg.OrderNo,
		arg.UserID,
		arg.TotalCents,
		arg.ExpiredAt,
	)
}

const paymentIntentByRequest = `-- name: PaymentIntentByRequest :one
SELECT intent_id, merchant_order_no, payment_order_id, user_id, openid,
       device_id, port_no, port_code, station_id, pricing_rule_id,
       pricing_rule_version, pricing_snapshot, estimated_kwh,
       estimated_minutes, electric_cents, service_cents, total_cents,
       charge_mode, charge_quantity, status, expires_at
FROM charge_payment_intent
WHERE user_id = ? AND client_request_id = ? LIMIT 1
`

type PaymentIntentByRequestParams struct {
	UserID          uint64
	ClientRequestID string
}

type PaymentIntentByRequestRow struct {
	IntentID           string
	MerchantOrderNo    string
	PaymentOrderID     uint64
	UserID             uint64
	Openid             string
	DeviceID           string
	PortNo             uint8
	PortCode           string
	StationID          uint64
	PricingRuleID      uint64
	PricingRuleVersion uint32
	PricingSnapshot    json.RawMessage
	EstimatedKwh       string
	EstimatedMinutes   uint16
	ElectricCents      int64
	ServiceCents       int64
	TotalCents         int64
	ChargeMode         uint8
	ChargeQuantity     uint16
	Status             ChargePaymentIntentStatus
	ExpiresAt          time.Time
}

func (q *Queries) PaymentIntentByRequest(ctx context.Context, arg PaymentIntentByRequestParams) (PaymentIntentByRequestRow, error) {
	row := q.db.QueryRowContext(ctx, paymentIntentByRequest, arg.UserID, arg.ClientRequestID)
	var i PaymentIntentByRequestRow
	err := row.Scan(
		&i.IntentID,
		&i.MerchantOrderNo,
		&i.PaymentOrderID,
		&i.UserID,
		&i.Openid,
		&i.DeviceID,
		&i.PortNo,
		&i.PortCode,
		&i.StationID,
		&i.PricingRuleID,
		&i.PricingRuleVersion,
		&i.PricingSnapshot,
		&i.EstimatedKwh,
		&i.EstimatedMinutes,
		&i.ElectricCents,
		&i.ServiceCents,
		&i.TotalCents,
		&i.ChargeMode,
		&i.ChargeQuantity,
		&i.Status,
		&i.ExpiresAt,
	)
	return i, err
}

const userOpenID = `-- name: UserOpenID :one
SELECT openid FROM user WHERE id = ? AND status = 'active' AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) UserOpenID(ctx context.Context, id uint64) (string, error) {
	row := q.db.QueryRowContext(ctx, userOpenID, id)
	var openid string
	err := row.Scan(&openid)
	return openid, err
}
