CREATE TABLE IF NOT EXISTS charge_command (
  command_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  stop_command_id VARCHAR(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  charge_order_id BIGINT UNSIGNED NOT NULL,
  payment_order_id BIGINT UNSIGNED NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  device_id VARCHAR(64) NOT NULL,
  port_no TINYINT UNSIGNED NOT NULL,
  port_code VARCHAR(64) NOT NULL,
  port_id BIGINT UNSIGNED DEFAULT NULL,
  owns_port BOOLEAN NOT NULL DEFAULT FALSE,
  status ENUM('pending','sent','acked','stopping','rejected') NOT NULL DEFAULT 'pending',
  session_id VARCHAR(36) DEFAULT NULL,
  stop_session_id VARCHAR(36) DEFAULT NULL,
  sent_at DATETIME(3) DEFAULT NULL,
  stop_sent_at DATETIME(3) DEFAULT NULL,
  error VARCHAR(255) DEFAULT NULL,
  result_reported BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY(command_id),
  UNIQUE KEY uk_stop(stop_command_id),
  UNIQUE KEY uk_charge(charge_order_id),
  UNIQUE KEY uk_order(order_no),
  KEY idx_unreported(result_reported,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
