[package]
name = "common-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true
common-error = { path = "../common-error" }
common-config = { path = "../common-config" }
argon2.workspace = true
rand.workspace = true
hex.workspace = true
sha2.workspace = true
hmac.workspace = true
chrono.workspace = true
uuid.workspace = true
axum.workspace = true
tower-http.workspace = true
hyper.workspace = true
tracing.workspace = true
async-trait.workspace = true
base64 = "0.22"