CREATE TABLE IF NOT EXISTS charge_fee_receipt (
  charge_order_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  calculation_no VARCHAR(64) NOT NULL UNIQUE,
  result_json JSON NOT NULL,
  shortfall_cents BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
