CREATE TABLE IF NOT EXISTS charge_prepay (
  charge_order_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  request_json JSON NOT NULL,
  prepay_id VARCHAR(128) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
