CREATE TABLE IF NOT EXISTS wallet_risk_review (
 request_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
 actor_id BIGINT UNSIGNED NOT NULL,
 approved BOOLEAN NOT NULL,
 comment VARCHAR(255) NOT NULL,
 response_json JSON NOT NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
